name: Continuous Integration API

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: E2E Test
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          command: npm run test:e2e:ui:headless
